import {
  pageHead,
  SITE_NAME,
  LEGAL_ENTITY,
  LEGAL_ENTITY_LONG,
  BUSINESS_ADDRESS,
  GOVERNING_STATE,
} from "@/lib/seo";
import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader, SiteFooter } from "@/components/site-chrome";

export const Route = createFileRoute("/terms")({
  head: () =>
    pageHead({
      path: "/terms",
      title: "Terms of Service · GivenTake Goods Devs",
      description:
        "The terms that govern your use of the GivenTake Goods Devs website and any services provided.",
    }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen text-foreground antialiased">
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-6 py-20">
        <p className="text-[12px] font-semibold uppercase tracking-wider text-muted-ink">Legal</p>
        <h1 className="mt-2 font-display text-5xl font-medium tracking-tight text-ink">
          Terms of Service
        </h1>
        <p className="mt-3 text-[13px] text-muted-ink">
          Last updated:{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-ink">
          <Section title="1. Who you are contracting with">
            <p>
              {LEGAL_ENTITY_LONG}. References to "we", "us", and "{SITE_NAME}" in these terms mean
              that entity. Our business address is {BUSINESS_ADDRESS}.
            </p>
          </Section>

          <Section title="2. Acceptance">
            <p>
              By using this website you agree to these terms. If you don't agree, please don't use
              the site.
            </p>
            <p className="mt-3">
              These terms govern your use of the website only. Paid engagements are governed by a
              separate master services agreement and a signed statement of work. Where those
              documents conflict with anything on this page, the signed statement of work controls,
              then the master services agreement, then these terms.
            </p>
          </Section>

          <Section title="3. Use of the site">
            <p>
              You may browse and contact us through the site for lawful business purposes. You agree
              not to attempt to breach security, scrape at abusive rates, submit malicious content,
              or misrepresent your identity.
            </p>
          </Section>

          <Section title="4. Intellectual property">
            <p>
              All content on this site, including text, illustrations, and the "GivenTake" wordmark,
              is owned by {LEGAL_ENTITY} or licensed to us. You may not reuse it commercially
              without written permission.
            </p>
          </Section>

          <Section title="5. Illustrative material on this site">
            <p>
              The example builds, concept renders, and project descriptions shown on this site are
              illustrative of the kind of work we take on. They are labelled as such where they
              appear. They are not delivered client projects, they do not describe any identifiable
              client, and no outcome, performance level, timeline, or result is promised or implied
              by them. Any commitment about your project is made only in a signed statement of work.
            </p>
          </Section>

          <Section title="6. AI-assisted delivery">
            <p>
              We build with AI coding agents and other AI-assisted tools, and we review the output
              before it ships. That approach is disclosed up front, described on our homepage, and
              set out in full in the AI-use disclosure provided with every proposal.
            </p>
            <p className="mt-3">
              Two consequences are worth stating plainly. First, the legal status of copyright in
              AI-generated material is unsettled in the United States, so what we assign to a client
              is every right we hold in the delivered work — we do not warrant that an exclusive
              copyright exists in output generated by an AI system. Second, AI tools can reproduce
              third-party or open-source material; we run licence checks before delivery, but no
              such check is perfect. The specific warranties, exclusions, and remedies for a paid
              engagement live in the master services agreement, not on this page.
            </p>
          </Section>

          <Section title="7. Contact form">
            <p>
              Submissions are informational and not a binding contract. No engagement begins until
              both parties countersign a written statement of work. Do not send confidential,
              regulated, or sensitive personal information through the form.
            </p>
          </Section>

          <Section title="8. Third-party links">
            <p>
              The site may link to third-party sites. We are not responsible for their content or
              practices. Review their terms before using them.
            </p>
          </Section>

          <Section title="9. Disclaimers">
            <p>
              The site is provided "as is" without warranties of any kind, express or implied,
              including merchantability, fitness for a particular purpose, and non-infringement. We
              do not guarantee uninterrupted or error-free operation.
            </p>
          </Section>

          <Section title="10. Limitation of liability">
            <p>
              To the fullest extent permitted by law, {LEGAL_ENTITY} is not liable for indirect,
              incidental, consequential, or punitive damages arising from your use of the site. Our
              total liability for direct damages arising from the site is limited to USD 100, or the
              amount you have paid us in the past 12 months, whichever is greater. Liability for a
              paid engagement is governed by the master services agreement instead.
            </p>
            <p className="mt-3">
              Nothing in these terms excludes liability that cannot lawfully be excluded, including
              liability for fraud or fraudulent misrepresentation.
            </p>
          </Section>

          <Section title="11. Governing law">
            <p>
              These terms are governed by the laws of {GOVERNING_STATE}, without regard to
              conflict-of-laws principles. The exclusive venue for any dispute is the state and
              federal courts located in Ohio, and both parties consent to personal jurisdiction
              there, unless mandatory local consumer-protection law requires otherwise.
            </p>
          </Section>

          <Section title="12. Changes">
            <p>
              We may revise these terms. The "last updated" date shows when. Continued use after a
              change means you accept the updated terms.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              Questions about these terms:{" "}
              <a href="mailto:legal@giventake.dev" className="underline">
                legal@giventake.dev
              </a>
              .
            </p>
          </Section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-2xl font-medium tracking-tight text-ink">{title}</h2>
      <div className="mt-3 text-muted-ink">{children}</div>
    </section>
  );
}
