import test from "node:test";
import assert from "node:assert/strict";
import { createSupabaseDocumentStore } from "../src/server/documents/store.ts";

// The injected fetch is the whole point of the rewrite. The previous store took
// a @supabase/supabase-js client it built itself, so there was no seam: none of
// the behaviour below could be asserted without a live database.
const store = (handler) =>
  createSupabaseDocumentStore({
    url: "https://p.supabase.co",
    serviceRoleKey: "svc",
    fetch: handler,
  });

const ok = (body) => ({
  ok: true,
  status: 200,
  async json() {
    return body;
  },
});

const fail = (status) => ({
  ok: false,
  status,
  async json() {
    return {};
  },
});

const doc = {
  dealId: "d1",
  projectId: null,
  stageNumber: 4,
  docType: "sow",
  title: "SOW",
  body: "# SOW",
  bodyHash: "h1",
  templateId: "sow-v1",
  ownerId: null,
};

// --- createDocument --------------------------------------------------------

test("createDocument goes through the definer RPC and returns the new id", async () => {
  let seen;
  const s = store(async (url, init) => {
    seen = { url, init };
    return ok("11111111-1111-1111-1111-111111111111");
  });
  const id = await s.createDocument(doc);
  assert.equal(id, "11111111-1111-1111-1111-111111111111");
  assert.match(seen.url, /^https:\/\/p\.supabase\.co\/rest\/v1\/rpc\/document_create$/);
  assert.equal(seen.init.method, "POST");
});

test("createDocument maps camelCase input onto the RPC's p_ parameters", async () => {
  let body;
  const s = store(async (_url, init) => {
    body = JSON.parse(init.body);
    return ok("id-1");
  });
  await s.createDocument(doc);
  assert.equal(body.p_deal_id, "d1");
  assert.equal(body.p_project_id, null);
  assert.equal(body.p_stage_number, 4);
  assert.equal(body.p_doc_type, "sow");
  assert.equal(body.p_body_hash, "h1");
  assert.equal(body.p_template_id, "sow-v1");
  assert.equal(body.p_owner_id, null);
});

test("both auth headers carry the service-role key, and neither is omitted", async () => {
  // PostgREST needs apikey to route and Authorization to pick the role. One
  // without the other silently downgrades the caller to anon, which under RLS
  // with no policies reads as "row not found" rather than as an auth error.
  let seen;
  const s = store(async (_url, init) => {
    seen = init;
    return ok("id-1");
  });
  await s.createDocument(doc);
  assert.equal(seen.headers.apikey, "svc");
  assert.equal(seen.headers.Authorization, "Bearer svc");
  assert.equal(seen.headers["Content-Type"], "application/json");
});

test("a non-ok response throws, and the message names the rpc and the status", async () => {
  const s = store(async () => fail(500));
  await assert.rejects(
    () => s.createDocument(doc),
    (e) => {
      assert.match(e.message, /document rpc document_create failed: 500/);
      return true;
    },
  );
});

// --- updateDocumentBody ----------------------------------------------------

test("updateDocumentBody posts the new body and hash to its own RPC", async () => {
  let seen;
  const s = store(async (url, init) => {
    seen = { url, init };
    return { ok: true, status: 204, async json() {} };
  });
  await s.updateDocumentBody({ id: "x", body: "b2", bodyHash: "h2", status: "final" });
  assert.match(seen.url, /\/rpc\/document_update_body$/);
  const body = JSON.parse(seen.init.body);
  assert.equal(body.p_id, "x");
  assert.equal(body.p_body_hash, "h2");
  assert.equal(body.p_status, "final");
});

test("a void RPC answering 204 with no body is not treated as a failure", async () => {
  // PostgREST answers a `returns void` function with 204 and an empty payload.
  // Parsing that as JSON throws, which would turn a successful write into an
  // exception. Both void-returning methods here take that path.
  const s = store(async () => ({
    ok: true,
    status: 204,
    async json() {
      throw new SyntaxError("Unexpected end of JSON input");
    },
  }));
  await s.updateDocumentBody({ id: "x", body: "b", bodyHash: "h", status: "draft" });
  await s.markViewed("sig-1");
});

// --- createSignatureRequest ------------------------------------------------

test("createSignatureRequest returns the id and the token the RPC minted", async () => {
  // The token is generated by the database default, never by the caller, so the
  // only way to learn it is this return value.
  const s = store(async () => ok({ id: "sig-1", signing_token: "tok-abc" }));
  const r = await s.createSignatureRequest({
    documentId: "doc-1",
    recipientName: "Ada",
    recipientEmail: "ada@example.com",
    documentHash: "h1",
    sentBy: null,
  });
  assert.deepEqual(r, { id: "sig-1", signingToken: "tok-abc" });
});

// --- findByToken -----------------------------------------------------------

test("findByToken maps the joined row into the camelCase shape callers expect", async () => {
  const s = store(async () =>
    ok({
      id: "sig-1",
      document_id: "doc-1",
      recipient_name: "Ada",
      recipient_email: "ada@example.com",
      signing_token: "tok-abc",
      status: "pending",
      expires_at: "2999-01-01T00:00:00Z",
      signed_at: null,
      signed_name: null,
      document_hash: "h1",
      title: "SOW",
      body: "# SOW",
    }),
  );
  const row = await s.findByToken("tok-abc");
  assert.equal(row.id, "sig-1");
  assert.equal(row.documentId, "doc-1");
  assert.equal(row.recipientEmail, "ada@example.com");
  assert.equal(row.signingToken, "tok-abc");
  assert.equal(row.expiresAt, "2999-01-01T00:00:00Z");
  assert.equal(row.signedAt, null);
  assert.equal(row.documentHash, "h1");
  assert.equal(row.title, "SOW");
  assert.equal(row.body, "# SOW");
});

test("findByToken returns null when the RPC finds nothing", async () => {
  // An unknown token is an ordinary outcome - a stale link - not an error. The
  // sign page renders "not found" from this null.
  const s = store(async () => ok(null));
  assert.equal(await s.findByToken("nope"), null);
});

test("findByToken throws when the call itself fails", async () => {
  // Distinct from the null above on purpose: a 500 is not evidence that the
  // token is unknown, and answering "not found" would hide an outage behind a
  // plausible-looking page.
  const s = store(async () => fail(503));
  await assert.rejects(() => s.findByToken("tok-abc"), /document rpc document_find_by_token/);
});

// --- markSigned ------------------------------------------------------------

test("markSigned reports true when the database actually wrote the signature", async () => {
  let seen;
  const s = store(async (url, init) => {
    seen = { url, init };
    return ok(true);
  });
  const applied = await s.markSigned({
    id: "sig-1",
    signedName: "Ada Lovelace",
    consentText: "I agree",
    ip: "203.0.113.9",
    userAgent: "UA",
  });
  assert.equal(applied, true);
  assert.match(seen.url, /\/rpc\/document_mark_signed$/);
  const body = JSON.parse(seen.init.body);
  assert.equal(body.p_signed_name, "Ada Lovelace");
  assert.equal(body.p_consent_text, "I agree");
  assert.equal(body.p_ip, "203.0.113.9");
  assert.equal(body.p_user_agent, "UA");
});

test("markSigned reports false when the row was already signed", async () => {
  // This is the replay guard surfacing. A resubmitted POST must be able to tell
  // that its write did not land, so it can answer "already signed" instead of
  // pretending it recorded a second signature.
  const s = store(async () => ok(false));
  assert.equal(
    await s.markSigned({
      id: "sig-1",
      signedName: "Ada",
      consentText: "I agree",
      ip: null,
      userAgent: null,
    }),
    false,
  );
});

test("markSigned throws on a failed call rather than reporting a write it cannot confirm", async () => {
  const s = store(async () => fail(500));
  await assert.rejects(
    () =>
      s.markSigned({
        id: "sig-1",
        signedName: "Ada",
        consentText: "I agree",
        ip: null,
        userAgent: null,
      }),
    /document rpc document_mark_signed failed: 500/,
  );
});

// --- dealHasSignedSow: the one method that fails closed --------------------

test("dealHasSignedSow passes the RPC's true through", async () => {
  let seen;
  const s = store(async (url, init) => {
    seen = { url, init };
    return ok(true);
  });
  assert.equal(await s.dealHasSignedSow("deal-1"), true);
  assert.match(seen.url, /\/rpc\/deal_has_signed_sow$/);
  assert.equal(JSON.parse(seen.init.body).p_deal_id, "deal-1");
});

test("dealHasSignedSow returns false when the RPC says no", async () => {
  const s = store(async () => ok(false));
  assert.equal(await s.dealHasSignedSow("deal-1"), false);
});

test("dealHasSignedSow returns false when the call errors out", async () => {
  // The case that matters. This is stage 4's gate - "Signed and paid before any
  // code". A gate that cannot verify must not pass.
  const s = store(async () => {
    throw new TypeError("fetch failed");
  });
  assert.equal(await s.dealHasSignedSow("deal-1"), false);
});

test("dealHasSignedSow returns false on a non-ok response", async () => {
  const s = store(async () => fail(500));
  assert.equal(await s.dealHasSignedSow("deal-1"), false);
});

test("dealHasSignedSow returns false when the RPC answers with anything but true", async () => {
  // A null - which is what a definer function returns if it ever stops
  // returning a boolean - must not be coerced into a pass.
  for (const answer of [null, undefined, "true", 1, {}]) {
    const s = store(async () => ok(answer));
    assert.equal(await s.dealHasSignedSow("deal-1"), false, `${JSON.stringify(answer)} passed`);
  }
});

// --- the architectural constraint itself -----------------------------------

test("the store imports no auth SDK and reaches no table directly", async () => {
  // @supabase/supabase-js is not a dependency of this repo - zero hits in
  // package.json and bun.lock - so an import of it survives only while a stray
  // copy sits in node_modules, and dies on a frozen install. The prose mention
  // in the file's header comment is allowed; an import is not.
  const { readFileSync } = await import("node:fs");
  const src = readFileSync("src/server/documents/store.ts", "utf8");
  assert.doesNotMatch(src, /(?:import|require)\b[^;\n]*["']@supabase\/supabase-js["']/);
  // Direct table access is what the definer RPCs exist to prevent: RLS is on
  // for both tables with no policies, so /rest/v1/documents reads as empty
  // rather than as an error.
  assert.doesNotMatch(src, /\/rest\/v1\/(?!rpc\/)/);
});
