import {
  IconBot,
  IconTest,
  IconLock,
  IconReview,
} from "@/components/marks";

const guardrails = [
  {
    title: "AI output is verified",
    body: "Every line generated by an AI agent is read, tested, and refined before it ships. I don't trust output I can't explain. If the AI produces something that doesn't match the plan, it gets rewritten.",
    Icon: IconBot,
  },
  {
    title: "Automated tests run before review",
    body: "I write tests for the critical paths: user flows, API contracts, and edge cases. Tests run on every change. A failing test means nothing moves forward.",
    Icon: IconTest,
  },
  {
    title: "Security is built in",
    body: "No secrets in code, strict input validation, least-privilege access, and dependency checks for known vulnerabilities. If something is outside my comfort zone, I bring in a specialist or tell you upfront.",
    Icon: IconLock,
  },
  {
    title: "Human review at every gate",
    body: "AI handles the boilerplate. I handle architecture, UX, and final sign-off. You talk to the same person from kickoff to launch, and nothing ships without my manual review.",
    Icon: IconReview,
  },
];

export function QualityGuardrails() {
  return (
    <section id="guardrails" className="border-b border-hairline bg-secondary/50">
      <div className="mx-auto max-w-7xl px-6 py-24 md:py-28">
        <div className="mb-14 max-w-2xl">
          <p className="text-[13px] font-medium text-violet">Quality & Guardrails</p>
          <h2 className="mt-3 font-display text-4xl font-medium leading-[1.02] tracking-[-0.03em] text-ink md:text-5xl">
            AI speeds up the work. These guardrails keep it reliable.
          </h2>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {guardrails.map((g) => (
            <article
              key={g.title}
              className="group rounded-2xl border border-hairline bg-white p-6 transition hover:shadow-soft"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-secondary text-ink transition group-hover:bg-violet-soft group-hover:text-violet">
                <g.Icon className="h-5 w-5" />
              </div>
              <h3 className="mt-5 text-[18px] font-semibold tracking-tight text-ink">
                {g.title}
              </h3>
              <p className="mt-2 text-[14.5px] leading-relaxed text-muted-ink">
                {g.body}
              </p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
