import { Link } from "@tanstack/react-router";
import { Reveal } from "@/components/reveal";
import { IconBot, IconTest, IconLock, IconReview, IconArrowRight } from "@/components/marks";

const guardrails = [
  {
    title: "AI output is verified",
    body: "Every line generated by an AI agent is read, tested, and refined before it ships. We don't trust output we can't explain. If the AI produces something that doesn't match the plan, it gets rewritten.",
    Icon: IconBot,
  },
  {
    title: "Automated tests run before review",
    body: "We write tests for the critical paths: user flows, API contracts, and edge cases. Tests run on every change. A failing test means nothing moves forward.",
    Icon: IconTest,
  },
  {
    title: "Security is built in",
    body: "No secrets in code, strict input validation, least-privilege access, and dependency checks for known vulnerabilities. If something falls outside what we can do well, we bring in a specialist or tell you upfront.",
    Icon: IconLock,
  },
  {
    title: "Human review at every gate",
    body: "AI handles the boilerplate. We handle architecture, UX, and final sign-off. You deal with the studio directly from kickoff to launch, and nothing ships without manual human review.",
    Icon: IconReview,
  },
];

export function QualityGuardrails() {
  return (
    <section id="guardrails" className="border-b border-hairline bg-secondary/50">
      <div className="mx-auto max-w-7xl px-6 py-24 md:py-28">
        <Reveal className="mb-14 max-w-2xl">
          <p className="text-[13px] font-medium text-violet">Quality & Guardrails</p>
          <h2 className="mt-3 font-display text-4xl font-medium leading-[1.02] tracking-[-0.03em] text-ink md:text-5xl">
            AI speeds up the work. These guardrails keep it reliable.
          </h2>
        </Reveal>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {guardrails.map((g, i) => (
            <Reveal key={g.title} delay={i * 70}>
              <article className="card-lift group h-full rounded-2xl border border-hairline bg-white p-6">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-secondary text-ink transition group-hover:bg-violet-soft group-hover:text-violet">
                  <g.Icon className="h-5 w-5" />
                </div>
                <h3 className="mt-5 text-[18px] font-semibold tracking-tight text-ink">
                  {g.title}
                </h3>
                <p className="mt-2 text-[14.5px] leading-relaxed text-muted-ink">{g.body}</p>
              </article>
            </Reveal>
          ))}
        </div>

        <Reveal delay={120}>
          <div className="mt-10 flex flex-wrap items-center gap-x-7 gap-y-3">
            <Link
              to="/how-we-use-ai"
              className="btn-icon-nudge inline-flex items-center gap-1.5 text-[14px] font-medium text-violet"
            >
              Exactly how we use AI
              <IconArrowRight className="h-4 w-4" />
            </Link>
            <Link
              to="/process"
              className="btn-icon-nudge inline-flex items-center gap-1.5 text-[14px] font-medium text-violet"
            >
              The process every project runs through
              <IconArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
