/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'
import { Route as ApiIngestV1LeadsRouteImport } from './routes/api.ingest.v1.leads'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const ApiIngestV1LeadsRoute = ApiIngestV1LeadsRouteImport.update({
  id: '/api/ingest/v1/leads',
  path: '/api/ingest/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/ingest/v1/leads': typeof ApiIngestV1LeadsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/ingest/v1/leads': typeof ApiIngestV1LeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/ingest/v1/leads': typeof ApiIngestV1LeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-tenant'
    | '/leads'
    | '/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/leads/$leadId'
    | '/api/ingest/v1/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/select-tenant'
    | '/leads'
    | '/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/'
    | '/leads/$leadId'
    | '/api/ingest/v1/leads'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/select-tenant'
    | '/_app/leads'
    | '/_app/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/_app/'
    | '/_app/leads/$leadId'
    | '/api/ingest/v1/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectTenantRoute: typeof SelectTenantRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiIngestV1LeadsRoute: typeof ApiIngestV1LeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/api/ingest/v1/leads': {
      id: '/api/ingest/v1/leads'
      path: '/api/ingest/v1/leads'
      fullPath: '/api/ingest/v1/leads'
      preLoaderRoute: typeof ApiIngestV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectTenantRoute: SelectTenantRoute,
  AdminSupportRoute: AdminSupportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiIngestV1LeadsRoute: ApiIngestV1LeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
