/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DataRequestRouteImport } from './routes/data-request'
import { Route as DoNotSellRouteImport } from './routes/do-not-sell'
import { Route as HowWeUseAiRouteImport } from './routes/how-we-use-ai'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StudioSignInRouteImport } from './routes/studio.sign-in'
import { Route as StudioAuthCallbackRouteImport } from './routes/studio.auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRequestRoute = DataRequestRouteImport.update({
  id: '/data-request',
  path: '/data-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DoNotSellRoute = DoNotSellRouteImport.update({
  id: '/do-not-sell',
  path: '/do-not-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeUseAiRoute = HowWeUseAiRouteImport.update({
  id: '/how-we-use-ai',
  path: '/how-we-use-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSignInRoute = StudioSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAuthCallbackRoute = StudioAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/studio/sign-in': typeof StudioSignInRoute
  '/articles/': typeof ArticlesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/studio/auth/callback': typeof StudioAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/studio/sign-in': typeof StudioSignInRoute
  '/articles': typeof ArticlesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/studio/auth/callback': typeof StudioAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/studio/sign-in': typeof StudioSignInRoute
  '/articles/': typeof ArticlesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/studio/auth/callback': typeof StudioAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/data-request'
    | '/do-not-sell'
    | '/how-we-use-ai'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/articles/$slug'
    | '/services/$slug'
    | '/studio/sign-in'
    | '/articles/'
    | '/services/'
    | '/studio/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/data-request'
    | '/do-not-sell'
    | '/how-we-use-ai'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/articles/$slug'
    | '/services/$slug'
    | '/studio/sign-in'
    | '/articles'
    | '/services'
    | '/studio/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/cookies'
    | '/data-request'
    | '/do-not-sell'
    | '/how-we-use-ai'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/articles/$slug'
    | '/services/$slug'
    | '/studio/sign-in'
    | '/articles/'
    | '/services/'
    | '/studio/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  CookiesRoute: typeof CookiesRoute
  DataRequestRoute: typeof DataRequestRoute
  DoNotSellRoute: typeof DoNotSellRoute
  HowWeUseAiRoute: typeof HowWeUseAiRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  TermsRoute: typeof TermsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-request': {
      id: '/data-request'
      path: '/data-request'
      fullPath: '/data-request'
      preLoaderRoute: typeof DataRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-not-sell': {
      id: '/do-not-sell'
      path: '/do-not-sell'
      fullPath: '/do-not-sell'
      preLoaderRoute: typeof DoNotSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-use-ai': {
      id: '/how-we-use-ai'
      path: '/how-we-use-ai'
      fullPath: '/how-we-use-ai'
      preLoaderRoute: typeof HowWeUseAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/sign-in': {
      id: '/studio/sign-in'
      path: '/sign-in'
      fullPath: '/studio/sign-in'
      preLoaderRoute: typeof StudioSignInRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/auth/callback': {
      id: '/studio/auth/callback'
      path: '/auth/callback'
      fullPath: '/studio/auth/callback'
      preLoaderRoute: typeof StudioAuthCallbackRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioSignInRoute: typeof StudioSignInRoute
  StudioAuthCallbackRoute: typeof StudioAuthCallbackRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSignInRoute: StudioSignInRoute,
  StudioAuthCallbackRoute: StudioAuthCallbackRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  CookiesRoute: CookiesRoute,
  DataRequestRoute: DataRequestRoute,
  DoNotSellRoute: DoNotSellRoute,
  HowWeUseAiRoute: HowWeUseAiRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  TermsRoute: TermsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
