/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OperatorDashboardRouteImport } from './routes/operator-dashboard'
import { Route as HowWeUseAiRouteImport } from './routes/how-we-use-ai'
import { Route as GuardrailsRouteImport } from './routes/guardrails'
import { Route as DoNotSellRouteImport } from './routes/do-not-sell'
import { Route as DataRequestRouteImport } from './routes/data-request'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CrmTeamRouteImport } from './routes/crm.team'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as CrmSendCheckRouteImport } from './routes/crm.send-check'
import { Route as CrmSearchRouteImport } from './routes/crm.search'
import { Route as CrmSamiRouteImport } from './routes/crm.sami'
import { Route as CrmReferralsRouteImport } from './routes/crm.referrals'
import { Route as CrmPlaybookRouteImport } from './routes/crm.playbook'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmMarketingRouteImport } from './routes/crm.marketing'
import { Route as CrmLoginRouteImport } from './routes/crm.login'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmDocumentsRouteImport } from './routes/crm.documents'
import { Route as CrmClientsRouteImport } from './routes/crm.clients'
import { Route as CrmApprovalsRouteImport } from './routes/crm.approvals'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CrmDealsIndexRouteImport } from './routes/crm.deals.index'
import { Route as CrmContactsIndexRouteImport } from './routes/crm.contacts.index'
import { Route as CrmCompaniesIndexRouteImport } from './routes/crm.companies.index'
import { Route as CrmLeadsIdRouteImport } from './routes/crm.leads.$id'
import { Route as CrmDealsIdRouteImport } from './routes/crm.deals.$id'
import { Route as CrmContactsIdRouteImport } from './routes/crm.contacts.$id'
import { Route as CrmCompaniesIdRouteImport } from './routes/crm.companies.$id'
import { Route as CrmAuthGoogleRouteImport } from './routes/crm.auth.google'
import { Route as CrmAuthCallbackRouteImport } from './routes/crm.auth.callback'
import { Route as ApiUnsubscribeTokenRouteImport } from './routes/api.unsubscribe.$token'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/operator-dashboard',
  path: '/operator-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeUseAiRoute = HowWeUseAiRouteImport.update({
  id: '/how-we-use-ai',
  path: '/how-we-use-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardrailsRoute = GuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const DoNotSellRoute = DoNotSellRouteImport.update({
  id: '/do-not-sell',
  path: '/do-not-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRequestRoute = DataRequestRouteImport.update({
  id: '/data-request',
  path: '/data-request',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTeamRoute = CrmTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSendCheckRoute = CrmSendCheckRouteImport.update({
  id: '/send-check',
  path: '/send-check',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSearchRoute = CrmSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSamiRoute = CrmSamiRouteImport.update({
  id: '/sami',
  path: '/sami',
  getParentRoute: () => CrmRoute,
} as any)
const CrmReferralsRoute = CrmReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPlaybookRoute = CrmPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMarketingRoute = CrmMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDocumentsRoute = CrmDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientsRoute = CrmClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CrmRoute,
} as any)
const CrmApprovalsRoute = CrmApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => CrmRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsIndexRoute = CrmDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIndexRoute = CrmContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCompaniesIndexRoute = CrmCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsIdRoute = CrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmLeadsRoute,
} as any)
const CrmDealsIdRoute = CrmDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIdRoute = CrmContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCompaniesIdRoute = CrmCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAuthGoogleRoute = CrmAuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAuthCallbackRoute = CrmAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => CrmRoute,
} as any)
const ApiUnsubscribeTokenRoute = ApiUnsubscribeTokenRouteImport.update({
  id: '/api/unsubscribe/$token',
  path: '/api/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRouteWithChildren
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/guardrails': typeof GuardrailsRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/operator-dashboard': typeof OperatorDashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/crm/approvals': typeof CrmApprovalsRoute
  '/crm/clients': typeof CrmClientsRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/playbook': typeof CrmPlaybookRoute
  '/crm/referrals': typeof CrmReferralsRoute
  '/crm/sami': typeof CrmSamiRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/send-check': typeof CrmSendCheckRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/team': typeof CrmTeamRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/unsubscribe/$token': typeof ApiUnsubscribeTokenRoute
  '/crm/auth/callback': typeof CrmAuthCallbackRoute
  '/crm/auth/google': typeof CrmAuthGoogleRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/deals/$id': typeof CrmDealsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/crm/contacts/': typeof CrmContactsIndexRoute
  '/crm/deals/': typeof CrmDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/guardrails': typeof GuardrailsRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/operator-dashboard': typeof OperatorDashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/crm/approvals': typeof CrmApprovalsRoute
  '/crm/clients': typeof CrmClientsRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/playbook': typeof CrmPlaybookRoute
  '/crm/referrals': typeof CrmReferralsRoute
  '/crm/sami': typeof CrmSamiRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/send-check': typeof CrmSendCheckRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/team': typeof CrmTeamRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/crm': typeof CrmIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/unsubscribe/$token': typeof ApiUnsubscribeTokenRoute
  '/crm/auth/callback': typeof CrmAuthCallbackRoute
  '/crm/auth/google': typeof CrmAuthGoogleRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/deals/$id': typeof CrmDealsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/companies': typeof CrmCompaniesIndexRoute
  '/crm/contacts': typeof CrmContactsIndexRoute
  '/crm/deals': typeof CrmDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRouteWithChildren
  '/data-request': typeof DataRequestRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/guardrails': typeof GuardrailsRoute
  '/how-we-use-ai': typeof HowWeUseAiRoute
  '/operator-dashboard': typeof OperatorDashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/crm/approvals': typeof CrmApprovalsRoute
  '/crm/clients': typeof CrmClientsRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/playbook': typeof CrmPlaybookRoute
  '/crm/referrals': typeof CrmReferralsRoute
  '/crm/sami': typeof CrmSamiRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/send-check': typeof CrmSendCheckRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/team': typeof CrmTeamRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/unsubscribe/$token': typeof ApiUnsubscribeTokenRoute
  '/crm/auth/callback': typeof CrmAuthCallbackRoute
  '/crm/auth/google': typeof CrmAuthGoogleRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/deals/$id': typeof CrmDealsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/crm/contacts/': typeof CrmContactsIndexRoute
  '/crm/deals/': typeof CrmDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/crm'
    | '/data-request'
    | '/do-not-sell'
    | '/guardrails'
    | '/how-we-use-ai'
    | '/operator-dashboard'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/terms'
    | '/work'
    | '/articles/$slug'
    | '/crm/approvals'
    | '/crm/clients'
    | '/crm/documents'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/marketing'
    | '/crm/pipeline'
    | '/crm/playbook'
    | '/crm/referrals'
    | '/crm/sami'
    | '/crm/search'
    | '/crm/send-check'
    | '/crm/tasks'
    | '/crm/team'
    | '/services/$slug'
    | '/articles/'
    | '/crm/'
    | '/services/'
    | '/api/unsubscribe/$token'
    | '/crm/auth/callback'
    | '/crm/auth/google'
    | '/crm/companies/$id'
    | '/crm/contacts/$id'
    | '/crm/deals/$id'
    | '/crm/leads/$id'
    | '/crm/companies/'
    | '/crm/contacts/'
    | '/crm/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/data-request'
    | '/do-not-sell'
    | '/guardrails'
    | '/how-we-use-ai'
    | '/operator-dashboard'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/terms'
    | '/work'
    | '/articles/$slug'
    | '/crm/approvals'
    | '/crm/clients'
    | '/crm/documents'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/marketing'
    | '/crm/pipeline'
    | '/crm/playbook'
    | '/crm/referrals'
    | '/crm/sami'
    | '/crm/search'
    | '/crm/send-check'
    | '/crm/tasks'
    | '/crm/team'
    | '/services/$slug'
    | '/articles'
    | '/crm'
    | '/services'
    | '/api/unsubscribe/$token'
    | '/crm/auth/callback'
    | '/crm/auth/google'
    | '/crm/companies/$id'
    | '/crm/contacts/$id'
    | '/crm/deals/$id'
    | '/crm/leads/$id'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/cookies'
    | '/crm'
    | '/data-request'
    | '/do-not-sell'
    | '/guardrails'
    | '/how-we-use-ai'
    | '/operator-dashboard'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/sitemap.xml'
    | '/terms'
    | '/work'
    | '/articles/$slug'
    | '/crm/approvals'
    | '/crm/clients'
    | '/crm/documents'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/marketing'
    | '/crm/pipeline'
    | '/crm/playbook'
    | '/crm/referrals'
    | '/crm/sami'
    | '/crm/search'
    | '/crm/send-check'
    | '/crm/tasks'
    | '/crm/team'
    | '/services/$slug'
    | '/articles/'
    | '/crm/'
    | '/services/'
    | '/api/unsubscribe/$token'
    | '/crm/auth/callback'
    | '/crm/auth/google'
    | '/crm/companies/$id'
    | '/crm/contacts/$id'
    | '/crm/deals/$id'
    | '/crm/leads/$id'
    | '/crm/companies/'
    | '/crm/contacts/'
    | '/crm/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  CookiesRoute: typeof CookiesRoute
  CrmRoute: typeof CrmRouteWithChildren
  DataRequestRoute: typeof DataRequestRoute
  DoNotSellRoute: typeof DoNotSellRoute
  GuardrailsRoute: typeof GuardrailsRoute
  HowWeUseAiRoute: typeof HowWeUseAiRoute
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiUnsubscribeTokenRoute: typeof ApiUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-dashboard': {
      id: '/operator-dashboard'
      path: '/operator-dashboard'
      fullPath: '/operator-dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-use-ai': {
      id: '/how-we-use-ai'
      path: '/how-we-use-ai'
      fullPath: '/how-we-use-ai'
      preLoaderRoute: typeof HowWeUseAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardrails': {
      id: '/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof GuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-not-sell': {
      id: '/do-not-sell'
      path: '/do-not-sell'
      fullPath: '/do-not-sell'
      preLoaderRoute: typeof DoNotSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-request': {
      id: '/data-request'
      path: '/data-request'
      fullPath: '/data-request'
      preLoaderRoute: typeof DataRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/team': {
      id: '/crm/team'
      path: '/team'
      fullPath: '/crm/team'
      preLoaderRoute: typeof CrmTeamRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/send-check': {
      id: '/crm/send-check'
      path: '/send-check'
      fullPath: '/crm/send-check'
      preLoaderRoute: typeof CrmSendCheckRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/search': {
      id: '/crm/search'
      path: '/search'
      fullPath: '/crm/search'
      preLoaderRoute: typeof CrmSearchRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/sami': {
      id: '/crm/sami'
      path: '/sami'
      fullPath: '/crm/sami'
      preLoaderRoute: typeof CrmSamiRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/referrals': {
      id: '/crm/referrals'
      path: '/referrals'
      fullPath: '/crm/referrals'
      preLoaderRoute: typeof CrmReferralsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/playbook': {
      id: '/crm/playbook'
      path: '/playbook'
      fullPath: '/crm/playbook'
      preLoaderRoute: typeof CrmPlaybookRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/marketing': {
      id: '/crm/marketing'
      path: '/marketing'
      fullPath: '/crm/marketing'
      preLoaderRoute: typeof CrmMarketingRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/documents': {
      id: '/crm/documents'
      path: '/documents'
      fullPath: '/crm/documents'
      preLoaderRoute: typeof CrmDocumentsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clients': {
      id: '/crm/clients'
      path: '/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof CrmClientsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/approvals': {
      id: '/crm/approvals'
      path: '/approvals'
      fullPath: '/crm/approvals'
      preLoaderRoute: typeof CrmApprovalsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals/': {
      id: '/crm/deals/'
      path: '/deals'
      fullPath: '/crm/deals/'
      preLoaderRoute: typeof CrmDealsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts/': {
      id: '/crm/contacts/'
      path: '/contacts'
      fullPath: '/crm/contacts/'
      preLoaderRoute: typeof CrmContactsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/companies/': {
      id: '/crm/companies/'
      path: '/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof CrmCompaniesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads/$id': {
      id: '/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof CrmLeadsIdRouteImport
      parentRoute: typeof CrmLeadsRoute
    }
    '/crm/deals/$id': {
      id: '/crm/deals/$id'
      path: '/deals/$id'
      fullPath: '/crm/deals/$id'
      preLoaderRoute: typeof CrmDealsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts/$id': {
      id: '/crm/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/crm/contacts/$id'
      preLoaderRoute: typeof CrmContactsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/companies/$id': {
      id: '/crm/companies/$id'
      path: '/companies/$id'
      fullPath: '/crm/companies/$id'
      preLoaderRoute: typeof CrmCompaniesIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/auth/google': {
      id: '/crm/auth/google'
      path: '/auth/google'
      fullPath: '/crm/auth/google'
      preLoaderRoute: typeof CrmAuthGoogleRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/auth/callback': {
      id: '/crm/auth/callback'
      path: '/auth/callback'
      fullPath: '/crm/auth/callback'
      preLoaderRoute: typeof CrmAuthCallbackRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/unsubscribe/$token': {
      id: '/api/unsubscribe/$token'
      path: '/api/unsubscribe/$token'
      fullPath: '/api/unsubscribe/$token'
      preLoaderRoute: typeof ApiUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmLeadsRouteChildren {
  CrmLeadsIdRoute: typeof CrmLeadsIdRoute
}

const CrmLeadsRouteChildren: CrmLeadsRouteChildren = {
  CrmLeadsIdRoute: CrmLeadsIdRoute,
}

const CrmLeadsRouteWithChildren = CrmLeadsRoute._addFileChildren(
  CrmLeadsRouteChildren,
)

interface CrmRouteChildren {
  CrmApprovalsRoute: typeof CrmApprovalsRoute
  CrmClientsRoute: typeof CrmClientsRoute
  CrmDocumentsRoute: typeof CrmDocumentsRoute
  CrmLeadsRoute: typeof CrmLeadsRouteWithChildren
  CrmLoginRoute: typeof CrmLoginRoute
  CrmMarketingRoute: typeof CrmMarketingRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmPlaybookRoute: typeof CrmPlaybookRoute
  CrmReferralsRoute: typeof CrmReferralsRoute
  CrmSamiRoute: typeof CrmSamiRoute
  CrmSearchRoute: typeof CrmSearchRoute
  CrmSendCheckRoute: typeof CrmSendCheckRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmTeamRoute: typeof CrmTeamRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmAuthCallbackRoute: typeof CrmAuthCallbackRoute
  CrmAuthGoogleRoute: typeof CrmAuthGoogleRoute
  CrmCompaniesIdRoute: typeof CrmCompaniesIdRoute
  CrmContactsIdRoute: typeof CrmContactsIdRoute
  CrmDealsIdRoute: typeof CrmDealsIdRoute
  CrmCompaniesIndexRoute: typeof CrmCompaniesIndexRoute
  CrmContactsIndexRoute: typeof CrmContactsIndexRoute
  CrmDealsIndexRoute: typeof CrmDealsIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmApprovalsRoute: CrmApprovalsRoute,
  CrmClientsRoute: CrmClientsRoute,
  CrmDocumentsRoute: CrmDocumentsRoute,
  CrmLeadsRoute: CrmLeadsRouteWithChildren,
  CrmLoginRoute: CrmLoginRoute,
  CrmMarketingRoute: CrmMarketingRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmPlaybookRoute: CrmPlaybookRoute,
  CrmReferralsRoute: CrmReferralsRoute,
  CrmSamiRoute: CrmSamiRoute,
  CrmSearchRoute: CrmSearchRoute,
  CrmSendCheckRoute: CrmSendCheckRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmTeamRoute: CrmTeamRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmAuthCallbackRoute: CrmAuthCallbackRoute,
  CrmAuthGoogleRoute: CrmAuthGoogleRoute,
  CrmCompaniesIdRoute: CrmCompaniesIdRoute,
  CrmContactsIdRoute: CrmContactsIdRoute,
  CrmDealsIdRoute: CrmDealsIdRoute,
  CrmCompaniesIndexRoute: CrmCompaniesIndexRoute,
  CrmContactsIndexRoute: CrmContactsIndexRoute,
  CrmDealsIndexRoute: CrmDealsIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  CookiesRoute: CookiesRoute,
  CrmRoute: CrmRouteWithChildren,
  DataRequestRoute: DataRequestRoute,
  DoNotSellRoute: DoNotSellRoute,
  GuardrailsRoute: GuardrailsRoute,
  HowWeUseAiRoute: HowWeUseAiRoute,
  OperatorDashboardRoute: OperatorDashboardRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiUnsubscribeTokenRoute: ApiUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
