-- Local operator-control foundation. Runtime roles receive no table grants: use reviewed narrow RPCs only.
create extension if not exists pgcrypto;
create type public.operator_mode as enum ('synthetic','shadow');
create type public.operator_run_status as enum ('running','awaiting_approval','completed','blocked','failed');

create table public.operator_system_control (id text primary key default 'global' check(id='global'), operators_enabled boolean not null default false, outbound_enabled boolean not null default false, updated_at timestamptz not null default now(), reason text not null default 'disabled by default');
create table public.operator_controls (operator_key text primary key check(operator_key ~ '^[a-z0-9_-]+$'), enabled boolean not null default false, allowed_modes public.operator_mode[] not null default '{}', updated_at timestamptz not null default now());
create table public.synthetic_datasets (id uuid primary key default gen_random_uuid(), name text not null unique, data jsonb not null default '{}' check(jsonb_typeof(data)='object'), created_at timestamptz not null default now());
create table public.clients (id uuid primary key default gen_random_uuid(), name text not null, ai_processing_allowed boolean not null default false, synthetic boolean not null default false, created_at timestamptz not null default now());
create table public.leads (id uuid primary key default gen_random_uuid(), email text not null, name text, synthetic boolean not null default false, created_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients, name text not null, synthetic boolean not null default false, created_at timestamptz not null default now());
create table public.touchpoints (id uuid primary key default gen_random_uuid(), lead_id uuid references public.leads, client_id uuid references public.clients, project_id uuid references public.projects, kind text not null, content jsonb not null default '{}', synthetic boolean not null default false, created_at timestamptz not null default now(), check(num_nonnulls(lead_id,client_id,project_id)>=1));
create table public.do_not_contact (id uuid primary key default gen_random_uuid(), normalized_address text not null unique, reason text not null, created_at timestamptz not null default now());
create table public.operator_runs (id uuid primary key default gen_random_uuid(), operator_key text not null references public.operator_controls, mode public.operator_mode not null, dataset_id uuid references public.synthetic_datasets, idempotency_key text not null unique, status public.operator_run_status not null default 'running', started_at timestamptz not null default now(), finished_at timestamptz, check(mode='shadow' or dataset_id is not null));
create table public.operator_approvals (id uuid primary key default gen_random_uuid(), run_id uuid not null references public.operator_runs, action text not null, payload_hash text not null check(payload_hash ~ '^[0-9a-f]{64}$'), payload jsonb not null, expires_at timestamptz not null, requested_at timestamptz not null default now(), approved_at timestamptz, revoked_at timestamptz, consumed_at timestamptz, check(expires_at>requested_at));
create table public.operator_audit_events (id bigint generated always as identity primary key, run_id uuid references public.operator_runs, operator_key text not null, event_type text not null, details jsonb not null default '{}', created_at timestamptz not null default now());
create index operator_runs_operator_started_idx on public.operator_runs(operator_key,started_at desc); create index approvals_run_idx on public.operator_approvals(run_id); create index audit_run_created_idx on public.operator_audit_events(run_id,created_at); create index leads_email_idx on public.leads(lower(email)); create index touchpoints_client_idx on public.touchpoints(client_id,created_at);

alter table public.operator_system_control enable row level security; alter table public.operator_controls enable row level security; alter table public.operator_runs enable row level security; alter table public.operator_approvals enable row level security; alter table public.operator_audit_events enable row level security; alter table public.synthetic_datasets enable row level security; alter table public.leads enable row level security; alter table public.clients enable row level security; alter table public.projects enable row level security; alter table public.touchpoints enable row level security; alter table public.do_not_contact enable row level security;
revoke all on table public.operator_system_control, public.operator_controls, public.operator_runs, public.operator_approvals, public.operator_audit_events, public.synthetic_datasets, public.leads, public.clients, public.projects, public.touchpoints, public.do_not_contact from anon, authenticated;
revoke all on sequence public.operator_audit_events_id_seq from anon, authenticated;
insert into public.operator_system_control(id) values('global');
comment on table public.operator_system_control is 'Single fail-closed global kill switch required by the agent operating charter.';
comment on table public.operator_controls is 'Fail-closed controls. Runtime access must use reviewed narrow SECURITY DEFINER RPCs, never direct table access.';
comment on table public.operator_audit_events is 'Append-only audit trail. Runtime writes must use append_operator_audit_event RPC.';

create function public.deny_audit_mutation() returns trigger language plpgsql as $$ begin raise exception 'audit events are append-only'; end $$;
create trigger operator_audit_no_update_delete before update or delete on public.operator_audit_events for each row execute function public.deny_audit_mutation();

create function public.check_operator_control(p_operator_key text,p_mode public.operator_mode) returns boolean language sql security definer set search_path=public,pg_temp stable as $$ select coalesce((select system.operators_enabled and control.enabled and p_mode=any(control.allowed_modes) from operator_system_control system cross join operator_controls control where system.id='global' and control.operator_key=p_operator_key),false) $$;
create function public.start_operator_run(p_operator_key text,p_mode public.operator_mode,p_dataset_id uuid,p_idempotency_key text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id uuid; begin if not check_operator_control(p_operator_key,p_mode) then raise exception 'operator disabled'; end if; if p_mode='synthetic' and p_dataset_id is null then raise exception 'synthetic dataset required'; end if; insert into operator_runs(operator_key,mode,dataset_id,idempotency_key) values(p_operator_key,p_mode,p_dataset_id,p_idempotency_key) returning id into v_id; return v_id; end $$;
create function public.append_operator_audit_event(p_run_id uuid,p_operator_key text,p_event_type text,p_details jsonb) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; begin if p_details is null or jsonb_typeof(p_details)<>'object' then raise exception 'object details required'; end if; insert into operator_audit_events(run_id,operator_key,event_type,details) values(p_run_id,p_operator_key,p_event_type,p_details) returning id into v_id; return v_id; end $$;
create function public.request_operator_approval(p_run_id uuid,p_action text,p_payload jsonb,p_payload_hash text,p_expires_at timestamptz) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id uuid; begin if p_action in ('send','deploy','set_price','change_scope','sign','refund') then raise exception 'hard prohibited action'; end if; if p_payload_hash !~ '^[0-9a-f]{64}$' or p_expires_at<=now() then raise exception 'invalid approval'; end if; insert into operator_approvals(run_id,action,payload,payload_hash,expires_at) values(p_run_id,p_action,p_payload,p_payload_hash,p_expires_at) returning id into v_id; return v_id; end $$;
revoke all on function public.check_operator_control(text,public.operator_mode), public.start_operator_run(text,public.operator_mode,uuid,text), public.append_operator_audit_event(uuid,text,text,jsonb), public.request_operator_approval(uuid,text,jsonb,text,timestamptz) from public;

-- Phase 3 narrow runtime/dashboard RPCs. Service role only; no browser role grants.
create table public.operator_idempotency (key text primary key, claimed_at timestamptz not null default now());
alter table public.operator_idempotency enable row level security;
revoke all on table public.operator_idempotency from anon, authenticated;

create function public.operator_get_controls(p_operator_key text) returns jsonb language sql security definer set search_path=public,pg_temp stable as $$
 select case when c.operator_key is null then null else jsonb_build_object('globalEnabled',s.operators_enabled,'enabled',c.enabled,'allowedModes',to_jsonb(c.allowed_modes)) end
 from operator_system_control s left join operator_controls c on c.operator_key=p_operator_key where s.id='global' $$;
create function public.operator_claim_idempotency(p_key text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin
 if p_key is null or length(p_key)<8 then raise exception 'invalid idempotency key'; end if;
 insert into operator_idempotency(key) values(p_key) on conflict do nothing; return found; end $$;
create function public.operator_is_suppressed(p_address text) returns boolean language sql security definer set search_path=public,pg_temp stable as $$
 select exists(select 1 from do_not_contact where normalized_address=lower(trim(p_address))) $$;
create function public.operator_client_allows_ai(p_client_id uuid) returns boolean language sql security definer set search_path=public,pg_temp stable as $$
 select coalesce((select synthetic and ai_processing_allowed from clients where id=p_client_id),false) $$;
create function public.operator_get_approval(p_id uuid) returns jsonb language sql security definer set search_path=public,pg_temp stable as $$
 select jsonb_build_object('id',id,'action',action,'payloadHash',payload_hash,'expiresAt',expires_at,'revokedAt',revoked_at,'consumedAt',consumed_at) from operator_approvals where id=p_id $$;
create function public.operator_consume_approval(p_id uuid,p_expected_hash text,p_at timestamptz) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin
 update operator_approvals set consumed_at=p_at where id=p_id and payload_hash=p_expected_hash and approved_at is not null and revoked_at is null and consumed_at is null and expires_at>p_at and action not in ('send','deploy','set_price','change_scope','sign','refund'); return found; end $$;
create function public.operator_dashboard_snapshot() returns jsonb language sql security definer set search_path=public,pg_temp stable as $$
 select jsonb_build_object('system',(select to_jsonb(s) from operator_system_control s where id='global'),'operators',coalesce((select jsonb_agg(to_jsonb(c)) from operator_controls c),'[]'),'runs',coalesce((select jsonb_agg(to_jsonb(r) order by started_at desc) from (select * from operator_runs where mode='synthetic' order by started_at desc limit 100) r),'[]'),'approvals',coalesce((select jsonb_agg(to_jsonb(a)) from operator_approvals a where approved_at is null and revoked_at is null and consumed_at is null and expires_at>now()),'[]'),'audit',coalesce((select jsonb_agg(to_jsonb(e)) from (select * from operator_audit_events order by created_at desc limit 200) e),'[]')) $$;
revoke all on function public.operator_get_controls(text),public.operator_claim_idempotency(text),public.operator_is_suppressed(text),public.operator_client_allows_ai(uuid),public.operator_get_approval(uuid),public.operator_consume_approval(uuid,text,timestamptz),public.operator_dashboard_snapshot() from public;
grant execute on function public.operator_get_controls(text),public.operator_claim_idempotency(text),public.operator_is_suppressed(text),public.operator_client_allows_ai(uuid),public.operator_get_approval(uuid),public.operator_consume_approval(uuid,text,timestamptz),public.operator_dashboard_snapshot() to service_role;
grant execute on function public.check_operator_control(text,public.operator_mode),public.start_operator_run(text,public.operator_mode,uuid,text),public.append_operator_audit_event(uuid,text,text,jsonb),public.request_operator_approval(uuid,text,jsonb,text,timestamptz) to service_role;
